# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_turma', models.CharField(max_length=1)),
                ('turno', models.CharField(max_length=15)),
                ('cursos', models.ManyToManyField(to='curriculo.Curso')),
                ('disciplina_ofertada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.DisciplinaOfertada')),
                ('matriculas', models.ManyToManyField(to='usuario.Aluno')),
                ('professores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Professor')),
            ],
        ),
    ]
